Repository boostorg/spirit, pull requests merged in 2025-05, with the labels that each got.

#803 Turn off -Werror in order to deal with unfixable upstream warnings
  .github/workflows/ci.yml
Labels: CI

#793 Proposal for solving fraction_part causing 1.09e-6 generated as 1.9e-6 issue #792
  include/boost/spirit/home/karma/numeric/real_policies.hpp
  test/karma/real3.cpp
Labels: bug

#791 Fix typo: 'implementation'
  doc/x3/tutorial/minimal.qbk
Labels: documentation

#770 Update syntax examples to parser operator docs
  doc/x3/quick_reference.qbk
Labels: documentation

#752 Remove shadow-field warnings.
  include/boost/spirit/home/qi/operator/expect.hpp
  include/boost/spirit/home/qi/operator/sequence.hpp
Labels: enhancement

#751 workaround for #750
  include/boost/spirit/home/x3/support/utility/error_reporting.hpp
Labels: enhancement

#693 Qi double parser IEEE 754 compliance warning
  doc/qi/numeric.qbk
Labels: documentation
